### PR TITLE
switch off capitalization

### PR DESCRIPTION
**Pull request by MrAntix**
some devices make the first char entered capital

### CODE REVIEW

**Comment by notwaldorf** [comment]
@MrAntix Thanks! Would you mind signing the CLA so I can merge this?

**Comment by MrAntix** [comment]
Signed it

**Comment by MrAntix** [comment]
not sure about those tests failing above?

when I go to the details, looks good, in fact says "Test run ended with great success" :D

**Comment by notwaldorf** [comment]
@MrAntix Tests are fine, don't worry about it. The CI runner status is a little moody these days :)

**Comment by MrAntix** [comment]
ok fab, thanks for your help

**Pull request merged**
